axiom01_drupal11.settings:
  type: config_object
  label: 'Axiom01 Drupal 11 theme settings'
  mapping:
    color_mode:
      type: string
      label: 'Color mode'
    color_palette:
      type: string
      label: 'Color palette'
    body_font:
      type: string
      label: 'Body font'
    heading_font:
      type: string
      label: 'Heading font'
    spacing_scale:
      type: string
      label: 'Spacing scale'
    layout_width:
      type: string
      label: 'Layout width'
    icon_set:
      type: string
      label: 'Icon set'
    character_set:
      type: string
      label: 'Character set'
